name: tdd_clean_architecture_number_trivia
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #service locator
  get_it: ^7.2.0
  #local cache
  shared_preferences: ^2.0.15
  #state management
  flutter_bloc: ^8.1.1
  #value equality
  equatable: ^2.0.5
  #funtional programming
  dartz: ^0.10.1
  #remote api
  http: ^0.13.5
  connectivity: ^3.0.6
  mocktail: ^0.3.0
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
